namespace ProducerConsumerScenarioUsingChannelsDemo
{
    public static class NewsFeed
    {
        // Priority 1 = Breaking, 2 = Important, 3 = Standard
        public static readonly List<NewsStory> Stories =
        [
            new() { Title = "Global AI Regulation Treaty Signed by 50 Nations",                         Priority = 1 },
            new() { Title = "Massive Earthquake Strikes Pacific Rim, Tsunami Warning Issued",           Priority = 1 },
            new() { Title = "US Federal Reserve Announces Emergency Interest Rate Cut",                 Priority = 1 },
            new() { Title = "Major Cyberattack Cripples European Power Grid",                          Priority = 1 },
            new() { Title = "Historic Peace Agreement Reached in Middle East",                          Priority = 1 },
            new() { Title = "WHO Declares New Respiratory Virus a Global Health Emergency",             Priority = 1 },
            new() { Title = "SpaceX Successfully Lands First Crewed Mission on Mars",                  Priority = 1 },
            new() { Title = "Nuclear Plant Leak Triggers Evacuation in Eastern Europe",                Priority = 1 },
            new() { Title = "Stock Markets Crash 15% in Worst Single-Day Drop Since 2008",            Priority = 1 },
            new() { Title = "Category 5 Hurricane Makes Landfall on US Gulf Coast",                   Priority = 1 },

            new() { Title = "NATO Expands Membership to Include Three New Countries",                  Priority = 2 },
            new() { Title = "Apple Unveils Neural Chip That Reads Brain Signals",                      Priority = 2 },
            new() { Title = "UN Climate Summit Agrees on Zero-Carbon Targets by 2040",                Priority = 2 },
            new() { Title = "China Launches First Permanent Lunar Research Base",                      Priority = 2 },
            new() { Title = "EU Passes Sweeping AI Liability Directive",                               Priority = 2 },
            new() { Title = "World's Largest Battery Storage Farm Goes Online in Australia",           Priority = 2 },
            new() { Title = "Breakthrough mRNA Cancer Vaccine Shows 90% Success Rate",                Priority = 2 },
            new() { Title = "Microsoft Acquires OpenAI in $200 Billion Deal",                         Priority = 2 },
            new() { Title = "UK Prime Minister Resigns Following No-Confidence Vote",                  Priority = 2 },
            new() { Title = "Global Water Shortage Crisis Declared by United Nations",                 Priority = 2 },
            new() { Title = "Autonomous Vehicles Approved for Nationwide Use in Germany",              Priority = 2 },
            new() { Title = "Scientists Confirm Discovery of Earth-Like Exoplanet",                   Priority = 2 },
            new() { Title = "Fusion Energy Plant Produces Net Positive Power for First Time",         Priority = 2 },
            new() { Title = "Amazon Rainforest Deforestation Reaches Critical Tipping Point",         Priority = 2 },
            new() { Title = "Federal Antitrust Case Forces Google to Divest YouTube",                 Priority = 2 },
            new() { Title = "Arctic Sea Ice Hits Record Low for Third Consecutive Year",              Priority = 2 },
            new() { Title = "Global Semiconductor Shortage Eases After New Fab Opens in Arizona",    Priority = 2 },
            new() { Title = "WHO Approves World's First Malaria-Eliminating Vaccine",                 Priority = 2 },
            new() { Title = "Quantum Computer Solves 10,000-Year Problem in 4 Minutes",              Priority = 2 },
            new() { Title = "BRICS Nations Launch Unified Digital Currency",                          Priority = 2 },

            new() { Title = "Paris Olympics Breaks All-Time Viewership Records",                      Priority = 3 },
            new() { Title = "New Study Links Ultra-Processed Foods to Early Cognitive Decline",       Priority = 3 },
            new() { Title = "Tesla Releases $15,000 Entry-Level Electric Vehicle",                    Priority = 3 },
            new() { Title = "Hollywood Writers Strike Ends After Six-Month Standoff",                 Priority = 3 },
            new() { Title = "Remote Work Becomes Permanent Policy at Fortune 500 Companies",          Priority = 3 },
            new() { Title = "Groundbreaking Alzheimer's Drug Gets FDA Fast-Track Approval",          Priority = 3 },
            new() { Title = "World Population Officially Surpasses 9 Billion",                       Priority = 3 },
            new() { Title = "TikTok Banned in Additional 12 Countries Over Data Concerns",           Priority = 3 },
            new() { Title = "NBA Expands to Europe with Two New Franchises",                          Priority = 3 },
            new() { Title = "Plastic Waste Cleanup Project Clears Half the Great Pacific Patch",     Priority = 3 },
            new() { Title = "Self-Repairing Road Material Deployed Across UK Motorways",             Priority = 3 },
            new() { Title = "Mexico City Unveils Largest Urban Vertical Farm in History",             Priority = 3 },
            new() { Title = "Boeing Debuts Hydrogen-Powered Commercial Airliner",                     Priority = 3 },
            new() { Title = "Gene Therapy Restores Hearing in Children Born Deaf",                   Priority = 3 },
            new() { Title = "Deepfake Detection Law Passed in United States Congress",               Priority = 3 },
            new() { Title = "Record 2 Million Electric Bikes Sold in US in Single Quarter",          Priority = 3 },
            new() { Title = "Scientists Grow Functional Human Kidney in Lab",                         Priority = 3 },
            new() { Title = "Antarctic Ice Sheet Collapse Risk Upgraded to High",                    Priority = 3 },
            new() { Title = "New Supersonic Passenger Jet Completes Transatlantic Trial",            Priority = 3 },
            new() { Title = "World's First Brain-Computer Interface Approved for Commercial Use",    Priority = 3 },
            new() { Title = "Global Inflation Drops Below 2% for First Time Since 2020",            Priority = 3 },
            new() { Title = "India Overtakes US as World's Second-Largest Economy",                  Priority = 3 },
            new() { Title = "Solar Energy Now Cheapest Power Source in 140 Countries",               Priority = 3 },
            new() { Title = "Robotic Surgery System Performs First Fully Autonomous Operation",      Priority = 3 },
            new() { Title = "Denmark Becomes First Country to Run on 100% Renewable Energy",        Priority = 3 },
            new() { Title = "Virtual Reality Classrooms Adopted by 50 Million Students Globally",   Priority = 3 },
            new() { Title = "Scientists Reverse Ageing Markers in Human Trial",                      Priority = 3 },
            new() { Title = "New York City Bans Single-Use Plastics Citywide",                      Priority = 3 },
            new() { Title = "Africa's First High-Speed Rail Network Opens in Nigeria",              Priority = 3 },
            new() { Title = "Drought Conditions Declared Across 30% of Western United States",     Priority = 3 },
            new() { Title = "Google Launches AI That Designs Its Own Successors",                   Priority = 3 },
            new() { Title = "European Space Agency Confirms Water Ice on Mercury's Surface",        Priority = 3 },
            new() { Title = "OpenAI Releases GPT-6 With Real-Time Multimodal Reasoning",           Priority = 3 },
            new() { Title = "World Chess Championship Won by 17-Year-Old AI-Trained Prodigy",      Priority = 3 },
            new() { Title = "Coral Reef Restoration Project Deemed a Scientific Success",           Priority = 3 },
            new() { Title = "Italy Passes Four-Day Work Week Law for All Employees",               Priority = 3 },
            new() { Title = "Underground City Opens Beneath Helsinki to Combat Harsh Winters",     Priority = 3 },
            new() { Title = "Record Wildfire Season Scorches Canadian Boreal Forest",              Priority = 3 },
            new() { Title = "Space Tourism Reaches 10,000 Passengers Milestone",                   Priority = 3 },
            new() { Title = "Global Coral Bleaching Event Declared by Climate Scientists",         Priority = 3 },
            new() { Title = "Digital Dollar Pilot Programme Launches in Three US States",          Priority = 3 },
            new() { Title = "Inflation Drives Record Rise in Urban Food Bank Demand",              Priority = 3 },
            new() { Title = "Vertical Axis Wind Turbines Installed on 1,000 City Rooftops",       Priority = 3 },
            new() { Title = "Social Media Minimum Age Raised to 16 Across European Union",        Priority = 3 },
            new() { Title = "Lab-Grown Meat Gets Supermarket Approval in Six Countries",          Priority = 3 },
            new() { Title = "New Battery Chemistry Charges EV in Under 5 Minutes",               Priority = 3 },
            new() { Title = "Japan's Birth Rate Falls to Historic Low for Fifth Year Running",    Priority = 3 },
            new() { Title = "3D-Printed Affordable Homes Deployed in Sub-Saharan Africa",        Priority = 3 },
            new() { Title = "Astronomers Detect Repeating Radio Signal from Nearby Star System", Priority = 3 },
            new() { Title = "Antibiotic-Resistant Superbug Outbreak Contained in Southeast Asia",Priority = 3 },
            new() { Title = "Largest Carbon Capture Plant Opens in Iceland",                      Priority = 3 },
            new() { Title = "Australia Commits to Phasing Out Coal by 2027",                     Priority = 3 },
            new() { Title = "AI-Generated Films Win Three Academy Awards",                        Priority = 3 },
            new() { Title = "Breakthrough in Room-Temperature Superconductors Confirmed",        Priority = 3 },
            new() { Title = "City of Dubai Completes World's Largest Desalination Plant",       Priority = 3 },
            new() { Title = "WHO Reports Global Obesity Rate Now Exceeds 1 Billion People",    Priority = 3 },
            new() { Title = "Cryptocurrency Regulation Framework Adopted by G20 Nations",      Priority = 3 },
            new() { Title = "First All-Female Crew Completes Circumnavigation by Sailboat",    Priority = 3 },
            new() { Title = "Pacific Island Nations Sue Big Oil for Climate Damages",          Priority = 3 },
            new() { Title = "Global Teacher Shortage Declared an Education Crisis",           Priority = 3 },
        ];
    }
}
